version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - aws s3 cp --recursive  . "s3://cloudops-repo.spehosting-ext.com" --acl public-read
  post_build:
   commands:
     - echo "post_build step"
 artifacts:
    type: zip
    files:
     - ./index.html
