version: 0.2
phases:
 install:
   commands:
     - echo "install step"
 pre_build:
   commands:
     - echo "pre_build step"
 build:
   commands:
     - npm build
 post_build:
   commands:
     - aws s3 cp --recursive --acl public-read  . s3://cloudops-repo.spehosting-ext.com 
 post_build:
   commands:
     - echo "post_build step"
